### ISSUE TITLE
ocp需要sudo免密权限问题

### ISSUE THREAD

**Issue by yonggang0929** [oceanbase/ocp-doc#7]
现在ocp管控需要主机的sudo免密权限， 而且这涉及到日常运维、主机监控等，长期sudo免密权限涉及安全操作问题， 后续能否降低用户权限要求呢， 比如后端实现采用交互式方式，用户拥有sudo权限即可，不需要免密

**Comment by dingdong6699** [comment]
您好~非常感谢您的关注！您提出的需求目前已在评审中，后续有进展我们会及时通知您哦~

**Comment by dingdong6699** [comment]
> 而现在occ和主机的sudo免密管控等涉及权限，需要长期权限，维护权限，长时间安全运维、监控等问题，可以不让权限运维呢，例行用户在日常操作中使用监控要求使用监控要求密，用户拥有sudo权限，无需免密

![1650942589452_42FA611F-729D-46ed-9D8E-32F0F000827F](https://user-images.githubusercontent.com/104408394/165214823-5db6d9b4-f5c5-44a4-a106-d2ad1c7ce55a.png)


> 而现在occ和主机的sudo免密管控等涉及权限，需要长期权限，维护权限，长时间安全运维、监控等问题，可以不让权限运维呢，例行用户在日常操作中使用监控要求使用监控要求密，用户拥有sudo权限，无需免密

您好，非常感谢您的关注！目前您提出的需求已在评审中，后续有进展我们会及时通知您哦~

**Comment by dingdong6699** [comment]
> 而现在occ和主机的sudo免密管控等涉及权限，需要长期权限，维护权限，长时间安全运维、监控等问题，可以不让权限运维呢，例行用户在日常操作中使用监控要求使用监控要求密，用户拥有sudo权限，无需免密

您好，非常感谢您的关注！目前您所提出的需求已在评审中，后续有进展我们会及时通知您~
